pipeline {
  agent any

  environment {
    SERVICE = 'appointment-service'
    DOCKER_REGISTRY = 'kumaran492414' 
    DOCKER_CREDENTIALS_ID = 'docker-creds'
    GIT_CREDENTIALS_ID = 'git-creds'
    GIT_REPO = 'https://github.com/Dharvi492414/Hospitalmanagement.git'
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', credentialsId: "${env.GIT_CREDENTIALS_ID}", url: "${env.GIT_REPO}"
      }
    }

    stage('Install & Build JS') {
      steps {
        dir("${SERVICE}") {
          sh 'npm install'
          sh 'npm run build'
        }
      }
    }

    stage('Docker Build') {
      steps {
        script {
          env.IMAGE_TAG = "${SERVICE}-${env.BUILD_NUMBER}"
          env.IMAGE_FULL = "${DOCKER_REGISTRY}/${SERVICE}:${IMAGE_TAG}"

          dir("appointment-service") {
             echo "Building Docker image: ${IMAGE_FULL}"
             sh "docker build -t ${IMAGE_FULL} ."
          }
        }
      }
    }

    stage('Docker Push') {
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
            sh "docker push ${IMAGE_FULL}"
          }
        }
      }
    }

    stage('Update Helm Chart') {
      steps {
        script {
          def valuesPath = "argo-deployments/apps/${SERVICE}/values.yaml"
          sh """
            sed -i 's|repository:.*|repository: ${DOCKER_REGISTRY}/${SERVICE}|' ${valuesPath}
            sed -i 's|tag:.*|tag: ${IMAGE_TAG}|' ${valuesPath}
          """
        }
      }
    }

    stage('Git Commit & Push') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: "${GIT_CREDENTIALS_ID}", usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
            sh '''
              git config user.name "$GIT_USER"
              git config user.email "g.kumaran1008@gmail.com"
              git add argo-deployments/apps/appointment-service/values.yaml
              git commit -m "Update appointment-service image tag to ${IMAGE_TAG}" || echo "No changes to commit"
              git push https://$GIT_USER:$GIT_TOKEN@github.com/Dharvi492414/Hospitalmanagement.git HEAD:main
             '''
           }
        }
      }
    }
  }
}